version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/mongo_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: its
      MONGO_INITDB_ROOT_PASSWORD: itsedx
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "27018:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: its
        ME_CONFIG_MONGODB_ADMINPASSWORD: itsedx
        ME_CONFIG_MONGODB_URL: mongodb://its:itsedx@mongodb:27017/
        ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

  ms_authn:
    build:
      context: ./ms_authn/.
      dockerfile: Dockerfile
    container_name: ms_authn
    ports:
      - 8000:5000
    command: npm run start:dev
    restart: always
    depends_on:
      - mongodb
    environment:
        DB_MONGODB_HOST: mongodb
        DB_MONGODB_PORT: 27017
        DB_USERNAME: its
        DB_PASSWORD: itsedx
        DB_MONGODB_NAME: plemas
    volumes:
      - ./ms_authn:/plemas/service
      - ./files:/plemas/service/uploads
ms_projects:
    build:
      context: ./ms_projects/.
      dockerfile: Dockerfile
    container_name: ms_projects
    ports:
      - 8001:5000
    command: npm run start:dev
    restart: always
    depends_on:
      - mongodb
    environment:
        DB_MONGODB_HOST: mongodb
        DB_MONGODB_PORT: 27017
        DB_USERNAME: its
        DB_PASSWORD: itsedx
        DB_MONGODB_NAME: plemas
    volumes:
      - ./ms_projects:/plemas/service
      - ./files:/plemas/service/src/uploads
