export const SUPERUSER_ROLE='superuser'
export const EMPLOYEE_ROLE='employee'
export const INTERVENANT_ROLE='intervenant '
export const PROJECT_MANAGER_ROLE='Chef_projet'
export const CLIENT_ROLE='client'
export const ALL_ROLES='all'